services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - TRIPO_API_KEY=${TRIPO_API_KEY:-}
      - NEWS_API_KEY=${NEWS_API_KEY:-7120175e997a4aae8edc62c5167858bf}
    volumes:
      - auto_data:/app/data
      - auto_models:/app/static/models/generated
 
volumes:
  auto_data:
  auto_models:
 